### PR TITLE
Use a more generic approach to handling arrays in JWT claims

### PR DESCRIPTION
**Pull request by WorldMaker**
Rather than using a one-off array claim build for the Roles claim and only the roles claim, apply a standardized approach for all JArray claims, which will match the behavior of other JWT parsing libraries better.

I was thinking about this in dealing with some other #55-related testing. This builds on #55, but is a larger breaking change if anyone was depending on the previous behavior (only the Roles claim expanding from an array), but again this better matches other JWT library behavior and any chance to remove a hardcoded one-off behavior for a generic reusable one is usually a good idea in my experience.

### CODE REVIEW

**Review by paule96 — APPROVED** [review]

**Comment by paule96** [comment]
but where is the breaking change? I don't see it. If I look to the code it looks like, that it only extended the current behavior.
For me there is no breaking change.

**Comment by kirkone** [comment]
Package [PR-56-KK.AspNetCore.EasyAuthAuthentication](https://dev.azure.com/kirkone/KK.AspNetCore.EasyAuthAuthentication/_packaging?_a=package&feed=KK.AspNetCore.EasyAuthAuthentication-PR&package=PR-56-KK.AspNetCore.EasyAuthAuthentication&protocolType=NuGet) published to [KK.AspNetCore.EasyAuthAuthentication-PR](https://dev.azure.com/kirkone/KK.AspNetCore.EasyAuthAuthentication/_packaging?_a=feed&feed=KK.AspNetCore.EasyAuthAuthentication-PR)

kirkone/KK.AspNetCore.EasyAuthAuthentication

**Comment by paule96** [comment]
cc @WorldMaker

**Comment by WorldMaker** [comment]
@paule96 Right, "breaking change" may be an overly strict interpretation. The claims produced here are very different after this change but use the same name, so anyone relying on the previous behavior will see very different results.

An example claim that would be effected is an `"emails"` claim. In a JWT like:

```json
{
  // ...
  "emails": [
    "test@example.com",
    "test@example.org"
  ],
  // ...
}
```

In the previous behavior there would be a single `"emails"` claim with the value `"[\n\"test@example.com\",\n\"test@example.org\"\n]" and in this updated behavior there would be two claims: `("emails", "test@example.com")` and `("emails", "test@example.org")`. It's a breaking change to anyone relying on there only being a single claim, for whatever reason, and for anyone expecting that embedded JSON string. I don't know who would want to rely on that behavior, but it is the sort of behavior people accidentally end up depending upon for all sorts of reasons.

I've been trained by some other projects to keep that sort of API change mentioned as a "breaking change" and keep it to its own PRs (and semver major bumps), even if the previous behavior was unexpected and basically wrong it was a part of the API contract.

In my specific case, in some shared authorization code I had to compensate for both the past "bad" "embedded JSON" behavior of this library and for Azure Functions producing claims the correct way, that prompted this PR to update the behavior. It would be nice to rip out the extra JSON parse when this releases.

**Comment by paule96** [comment]
@WorldMaker sorry I didn't respond so long but I has a busy week.

Hopefully I can take a look into this PR in more detail in the next 3 weeks. Hope you are not blocked if we don't release it so soon.

You can always use the PR feed from Azure Devops, so you can build your apps.

**Comment by paule96** [comment]
looks good to me. I will merge it.

**Comment by kirkone** [comment]
Package [PR-56-KK.AspNetCore.EasyAuthAuthentication](https://dev.azure.com/kirkone/KK.AspNetCore.EasyAuthAuthentication/_packaging?_a=package&feed=KK.AspNetCore.EasyAuthAuthentication-PR&package=PR-56-KK.AspNetCore.EasyAuthAuthentication&protocolType=NuGet) published to [KK.AspNetCore.EasyAuthAuthentication-PR](https://dev.azure.com/kirkone/KK.AspNetCore.EasyAuthAuthentication/_packaging?_a=feed&feed=KK.AspNetCore.EasyAuthAuthentication-PR)

kirkone/KK.AspNetCore.EasyAuthAuthentication

**Pull request merged**
