### PR TITLE
Add a ContainsKey check for Roles claim

### LINKED ISSUE #52: NullReferenceException with Bearer Token (No Roles Claims)
I'm seeing a NullReferenceException attempting to use Bearer Tokens (`/auth/me` `$[0].access_token`):

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at KK.AspNetCore.EasyAuthAuthentication.Services.EasyAuthForAuthorizationTokenService.BuildFromAuthToken(JObject xMsClientPrincipal, ProviderOptions options)
   at KK.AspNetCore.EasyAuthAuthentication.Services.EasyAuthForAuthorizationTokenService.AuthUser(HttpContext context, ProviderOptions options)
   at KK.AspNetCore.EasyAuthAuthentication.EasyAuthAuthenticationHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
```

I'm not seeing a similar error for other Authentication methods (`X-` headers or no headers when local). My current AAD setup, for whatever reason, is not returning any Roles claims and it looks like this is the only provider path with separate Role Claim ingestion.

### PR DESCRIPTION
**Pull request by WorldMaker**
Should fix #52

### CODE REVIEW

**Comment by paule96** [comment]
Hi @WorldMaker ,

Sorry for the late response. I will review this tomorrow. Thanks for your work. 👍
If you want you can add yourself in the Readme as bugfixer 😉

**Comment by paule96** [comment]
So I add a test to avoid that this breaks again. The change is approved 👍 Good job!

**Comment by paule96** [comment]
Okay that fix needs more time because our CI is broken... 🙄 

cc @kirkone please fix it. I don't have the required permissions

**Comment by kirkone** [comment]
I will have a look tomorrow

**Comment by kirkone** [comment]
Package [PR-53-KK.AspNetCore.EasyAuthAuthentication](https://dev.azure.com/kirkone/KK.AspNetCore.EasyAuthAuthentication/_packaging?_a=package&feed=KK.AspNetCore.EasyAuthAuthentication-PR&package=PR-53-KK.AspNetCore.EasyAuthAuthentication&protocolType=NuGet) published to [KK.AspNetCore.EasyAuthAuthentication-PR](https://dev.azure.com/kirkone/KK.AspNetCore.EasyAuthAuthentication/_packaging?_a=feed&feed=KK.AspNetCore.EasyAuthAuthentication-PR)

kirkone/KK.AspNetCore.EasyAuthAuthentication

**Pull request merged**
